[colors]
[colors.primary]
background = "#0b2641"
foreground = "#b2d6ff"

[colors.normal]
black = "#001d34"
white = "#9ec5fa"
red = "#cbc4f8"
green = "#4597b5"
yellow = "#b9d2a6"
blue = "#6b9fe0"
magenta = "#90c4ea"
cyan = "#5c8cc6"

[colors.selection]
background = "#4b6fa0"

[colors.cursor]
cursor = "#6b9fe0"
