[colors]
[colors.primary]
background = "#0b2d41"
foreground = "#b2ddff"

[colors.normal]
black = "#002434"
white = "#9eccfa"
red = "#cbcbf8"
green = "#459eb5"
yellow = "#b9d9a6"
blue = "#6ba6e0"
magenta = "#90cbea"
cyan = "#5c93c6"

[colors.selection]
background = "#4b76a0"

[colors.cursor]
cursor = "#6ba6e0"
